In [4]:
import pandas as pd

In [6]:
df = pd.read_csv('../all_listings.csv')

In [11]:
df.ape_id.value_counts()

ApeGang #203     181
ApeGang #6145    157
ApeGang #995     157
ApeGang #7237    133
ApeGang #28       73
                ...
ApeGang #3526      1
ApeGang #9632      1
ApeGang #2881      1
ApeGang #5922      1
ApeGang #1293      1
Name: ape_id, Length: 3273, dtype: int64

In [9]:
df.sort_values('listing_event_time', ascending=False)

,Unnamed: 0,ape_id,listing_event_id,listing_event_time,listing_price
0,0,ApeGang #8753,1456038549,2021-10-20T08:39:00.511655,1.2000
1,0,ApeGang #8801,1456010132,2021-10-20T08:36:41.715155,1.1000
2,0,ApeGang #3364,1456001428,2021-10-20T08:35:59.854256,3.5000
3,0,ApeGang #8685,1455956952,2021-10-20T08:32:28.327295,0.7918
4,0,ApeGang #8685,1455781111,2021-10-20T08:18:16.463918,0.8000
...,...,...,...,...,...
9975,0,ApeGang #4477,1197104153,2021-10-01T22:46:56.615752,0.3400
9976,0,ApeGang #9875,1197045312,2021-10-01T22:40:09.747936,0.3766
9977,0,ApeGang #429,1197009357,2021-10-01T22:36:10.218474,0.4051
9978,0,ApeGang #9875,1196939663,2021-10-01T22:29:09.177177,0.3772
9979,0,ApeGang #429,1196911386,2021-10-01T22:25:59.901502,0.4051

In [7]:
df[df.ape_id == 'ApeGang #9273']

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,ape_id,Clothes,Ears,Hat,Fur,Mouth,Eyes,listing_event_id,listing_event_time,listing_price
737,737,737,737,ApeGang #9273,Hotel Porter,NaN,Fireman,Brown,Nose Ring,Heart,1.441861e+09,2021-10-19 11:24:06.317005,0.85