In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../csvs/apes_with_listings.csv')

In [3]:
df.sort_values('listing_event_time', ascending=False)

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,ape_id,Clothes,Ears,Hat,Fur,Mouth,Eyes,listing_event_id,listing_event_time,listing_price
2448,2448,2448,2448,2448,ApeGang #7554,Winter Coat,NaN,Sushi Chef,Zebra,NaN,Round Glasses,1.455046e+09,2021-10-20 07:13:09.373034,0.850
1317,1317,1317,1317,1317,ApeGang #8685,NaN,NaN,Brown Beanie,Cream,Angry,Robot Glasses,1.454883e+09,2021-10-20 06:57:13.166920,0.900
7217,7217,7217,7217,7217,ApeGang #2815,Cop,Diamond Stud,NaN,Black,Drool Rainbow,NaN,1.454796e+09,2021-10-20 06:48:52.945100,0.777
4094,4094,4094,4094,4094,ApeGang #5911,Devil Wings,NaN,NaN,Brown,Angry,Monocle,1.454762e+09,2021-10-20 06:45:45.229975,4.300
6466,6466,6466,6466,6466,ApeGang #3533,Iron Man,NaN,Chef's,Tiger,Grin Rainbow,Diving Mask,1.454753e+09,2021-10-20 06:44:52.982721,1.600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,9993,9993,9993,9993,ApeGang #6,Lumberjack,NaN,Bandana,Black,Flames,Black Sunglasses,NaN,NaN,NaN
9994,9994,9994,9994,9994,ApeGang #5,Banana Shirt,NaN,NaN,Strong Dark Brown,NaN,NaN,NaN,NaN,NaN
9996,9996,9996,9996,9996,ApeGang #3,NaN,Silver Hoop,Chef's,Cream,Drool Rainbow,3D Glasses,NaN,NaN,NaN
9997,9997,9997,9997,9997,ApeGang #2,Military,Diamond Stud,Halo,Cream,NaN,Robot Glasses,NaN,NaN,NaN
9998,9998,9998,9998,9998,ApeGang #1,Red NBA Jersey,Diamond Stud,Party,Zebra,Baby Pacifier,Sad,NaN,NaN,NaN

In [7]:
df[df.ape_id == 'ApeGang #9273']

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,ape_id,Clothes,Ears,Hat,Fur,Mouth,Eyes,listing_event_id,listing_event_time,listing_price
737,737,737,737,ApeGang #9273,Hotel Porter,NaN,Fireman,Brown,Nose Ring,Heart,1.441861e+09,2021-10-19 11:24:06.317005,0.85